environment: demo
backend:
  image:
    tag: sha-19c2158
  replicaCount: 2
frontend:
  image:
    tag: sha-19c2158
  replicaCount: 2
config:
  NODE_ENV: production
  SUPABASE_URL: https://gwwasgxuhoeowhswqooj.supabase.co
ingress:
  clusterIssuer: letsencrypt-production
  hosts:
    app: demo.kmdndd.name.ng
    api: api.demo.kmdndd.name.ng
